export const plantList = [
  {
    id: 1,
    name: "Ancestor Buxus",
    img: "http://wallpapers.net/web/wallpapers/aloe-plant-hd-wallpaper/3840x2160.jpg",
    price: 650,
    water: 2,
    sun: 3,
  },
  {
    id: 2,
    name: "Spitfire Ragweed",
    img: "https://images8.alphacoders.com/407/407899.jpg",
    price: 245,
    water: 3,
    sun: 1,
  },
  {
    id: 3,
    name: "Green Stammerwort",
    img: "https://wallpapersmug.com/download/1920x1080/a5b9f1/summer-garden-plant-white.jpg",
    price: 350,
    water: 2,
    sun: 2,
  },
  {
    id: 4,
    name: "Ancestor Buxus",
    img: "http://wallpapers.net/web/wallpapers/aloe-plant-hd-wallpaper/3840x2160.jpg",
    price: 650,
    water: 2,
    sun: 3,
  },
  {
    id: 5,
    name: "Spitfire Ragweed",
    img: "https://images8.alphacoders.com/407/407899.jpg",
    price: 245,
    water: 3,
    sun: 1,
  },
];
